'use strict';
// The scaffold generator. From a dossier it emits a STARTING POINT for the two
// files a landing hand-writes from scratch today: the sitegating test and the
// strict fake. It fills in the captured facts (real token URLs, refuse routes,
// observed schemas, history-shaped pollution keys) and marks every spot that
// needs human judgment with a TODO. It never writes into extension/ — output
// lands in recon-data/sites/<id>/scaffold/ (gitignored); the human reads,
// confirms against the dossier, and copies in. A scaffold is a draft, never a
// lock: the mutation-proof discipline (docs/ADDING-A-SITE.md) still applies.

const fs = require('node:fs');
const path = require('node:path');

function readJson(file, fallback) {
  try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return fallback; }
}

// Captured strings are UNTRUSTED (a token symbol, a URL, a JSON key from a
// hostile site). They must never break out of the generated JS. jsStr emits a
// safe string literal; commentSafe strips newlines so a value cannot escape a
// // comment into executable code.
function jsStr(s) { return JSON.stringify(String(s == null ? '' : s)); }
function commentSafe(s) { return String(s == null ? '' : s).replace(/[\r\n\t\u2028\u2029]+/g, ' ').replace(/\s+/g, ' ').trim(); }

function scaffold(dossierDir, outDir, siteId) {
  const corpus = readJson(path.join(dossierDir, 'corpus.json'), { urls: [] });
  const endpoints = readJson(path.join(dossierDir, 'endpoints.json'), []);
  const ws = readJson(path.join(dossierDir, 'ws.json'), []);
  fs.mkdirSync(outDir, { recursive: true });

  const gatingTest = renderGatingTest(siteId, corpus);
  const fakeStub = renderFakeStub(siteId, endpoints, ws);
  fs.writeFileSync(path.join(outDir, `${siteId}.gating.test.js`), gatingTest);
  fs.writeFileSync(path.join(outDir, `${siteId}.fake.stub.js`), fakeStub);

  return {
    files: [`${siteId}.gating.test.js`, `${siteId}.fake.stub.js`],
    tokenPages: (corpus.urls || []).filter((u) => u.looksTokenPage).length,
    refuseRoutes: (corpus.urls || []).filter((u) => u.looksHistoryPage || (u.looksListPage && !u.looksTokenPage)).length,
    endpoints: endpoints.length,
    wsChannels: ws.length,
  };
}

function renderGatingTest(siteId, corpus) {
  const urls = corpus.urls || [];
  const tokenPages = urls.filter((u) => u.looksTokenPage);
  const refuseRoutes = urls.filter((u) => u.looksHistoryPage || (u.looksListPage && !u.looksTokenPage));

  const L = [];
  const p = (s = '') => L.push(s);
  p(`/* GENERATED by pt-recon — a STARTING POINT for ${siteId}'s gating lock, not a`);
  p(` * finished test. Every row below came from a real capture; CONFIRM each`);
  p(` * against docs/ADDING-A-SITE.md and the live site before trusting it, and`);
  p(` * prove the lock can fail (mutate the exact match()/detect() line, watch`);
  p(` * this go red) before landing. Copy into extension/test/${siteId}.test.js.`);
  p(` */`);
  p(`'use strict';`);
  p(`const test = require('node:test');`);
  p(`const assert = require('node:assert/strict');`);
  p(`const fs = require('node:fs');`);
  p(`const path = require('node:path');`);
  p(`const vm = require('node:vm');`);
  p('');
  p(`const SRC = fs.readFileSync(path.join(__dirname, '..', 'sites.js'), 'utf8');`);
  p('');
  p(`function detectAt(href) {`);
  p(`  const url = new URL(href);`);
  p(`  const sandbox = { window: {}, self: {}, location: { href, hostname: url.hostname, pathname: url.pathname, search: url.search }, URL, URLSearchParams, console };`);
  p(`  vm.createContext(sandbox);`);
  p(`  vm.runInContext(SRC, sandbox, { filename: 'sites.js' });`);
  p(`  const site = sandbox.window.PaperTrenchSites.currentSite();`);
  p(`  return { id: site.id, token: site.detect() };`);
  p(`}`);
  p('');
  p(`// Token pages that MUST mount. pt-recon saw an address in the path; you`);
  p(`// must confirm the expected kind ('mint' | 'pair') and that the address is`);
  p(`// the token's, not a wallet's.`);
  p(`const MOUNTS = [`);
  if (tokenPages.length) {
    for (const u of tokenPages.slice(0, 12)) {
      p(`  // ${u.hadLivePrice ? 'live price seen here' : 'NO live price seen — confirm this is a token page'}${u.chain ? ', chain=' + commentSafe(u.chain) : ''}`);
      p(`  [${jsStr(u.example)}, /* kind */ 'TODO', /* why */ 'captured token page'],`);
    }
  } else {
    p(`  // TODO: no token page was captured. Browse one and re-run capture/distill,`);
    p(`  //       then add [url, kind, why] rows here. A gating lock without a`);
    p(`  //       positive row proves nothing.`);
  }
  p(`];`);
  p('');
  p(`// Routes that MUST refuse (O-10): wallets, holders, screeners, settings.`);
  p(`const REFUSALS = [`);
  if (refuseRoutes.length) {
    for (const u of refuseRoutes.slice(0, 12)) {
      p(`  [${jsStr(u.example)}, ${jsStr(u.looksHistoryPage ? 'history/wallet page (O-10)' : 'list/screener page')}],`);
    }
  } else {
    p(`  // TODO: no must-refuse route captured. Browse a wallet/holders/settings`);
    p(`  //       page so this lock has negative rows.`);
  }
  p(`];`);
  p('');
  p(`test('${siteId}: token pages mount with the right kind', () => {`);
  p(`  for (const [href, kind, why] of MOUNTS) {`);
  p(`    const { token } = detectAt(href);`);
  p(`    assert.ok(token, why + ' → must mount: ' + href);`);
  p(`    assert.equal(token.kind, kind, why + ' → kind');`);
  p(`  }`);
  p(`});`);
  p('');
  p(`test('${siteId}: non-token routes refuse (O-10)', () => {`);
  p(`  for (const [href, why] of REFUSALS) {`);
  p(`    const { token } = detectAt(href);`);
  p(`    assert.equal(token, null, why + ' → must refuse: ' + href);`);
  p(`  }`);
  p(`});`);
  p('');
  return L.join('\n');
}

function renderFakeStub(siteId, endpoints, ws) {
  const L = [];
  const p = (s = '') => L.push(s);
  p(`/* GENERATED by pt-recon — a reference for ${siteId}'s strict fake, NOT a`);
  p(` * finished fake. It lists the endpoint/WS shapes the capture actually saw.`);
  p(` * F-39: implement ONLY what was observed over the wire. A fake method the`);
  p(` * site never served is how a suite stays green while the site draws nothing.`);
  p(` * Prices in trades/holders/positions payloads are HISTORY — they must never`);
  p(` * tick the live price (see the dossier §6 pollution keys).`);
  p(` */`);
  p('');
  if (endpoints.length) {
    p(`// ---- REST endpoints observed (method pattern — status — schema) ----`);
    for (const e of endpoints.filter((x) => x.schema).slice(0, 10)) {
      p(commentSafe(`// ${e.method} ${e.host}${e.pattern}  [${Object.keys(e.statuses || {}).join(',') || '?'}]${e.auth ? ' auth' : ''}`));
      if (e.fixtureRef) p(commentSafe(`//   fixture: ${path.basename(e.fixtureRef)}`));
      for (const line of (e.schema || []).slice(0, 20)) p(commentSafe(`//     ${line}`));
      p('//');
    }
  } else {
    p(`// No JSON REST endpoints captured. If the site is REST-driven, extend the`);
    p(`// capture; if it is WS-driven, see below.`);
    p('');
  }
  if (ws.length) {
    p(`// ---- WebSocket channels observed (host — frames — discriminators) ----`);
    for (const c of ws.slice(0, 6)) {
      p(commentSafe(`// ${c.url}  frames=${c.frames} rate/min≈${Math.round(c.ratePerMin || 0)}`));
      if (c.discriminators && Object.keys(c.discriminators).length) p(commentSafe(`//   frame types: ${Object.keys(c.discriminators).slice(0, 8).join(', ')}`));
      for (const line of (c.schema || []).slice(0, 16)) p(commentSafe(`//     ${line}`));
      p('//');
    }
  } else {
    p(`// No WS/SSE channels captured. If the live price ticks over a socket, the`);
    p(`// capture missed it — browse a token page with a live chart and re-capture.`);
  }
  p('');
  p(`// TODO: build the strict fake from the shapes above + the fixtures in the`);
  p(`// dossier's fixtures/ dir. Pair each price-shaped field with a lock proving`);
  p(`// the polluted shape never becomes a price candidate AND a genuine market`);
  p(`// snapshot still ticks (docs/ADDING-A-SITE.md, pair-form).`);
  p(`module.exports = {}; // <- replace with the fake`);
  p('');
  return L.join('\n');
}

module.exports = { scaffold };
